# Generated by Django 5.0.4 on 2024-04-05 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witch', '0002_remove_service_additional_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witch.service')),
            ],
        ),
    ]
