# Generated by Django 5.0.4 on 2024-04-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witch', '0003_additionaltext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='service',
        ),
    ]
